### PR TITLE
Add prev internal CA and "rackspace barbican" CA

### PR DESCRIPTION
**Pull request by itzg**
Retrieved from https://ssltool.rackspace.com/rscerts/

### CODE REVIEW

**Comment by goru97** [comment]
@itzg Not sure about the naming convention here, like rs_ca_level1.crt and rs_ca_level1.crt1. Is there a better way to name them so that one would know that one is the previous and the other is new, yet they are both valid.

**Comment by itzg** [comment]
@goru97 beyond my control. Those are the exact names published on the https://ssltool.rackspace.com/rscerts/ site and I don't want these file names to deviate from theirs.

**Comment by goru97** [comment]
Oh I see. No worries, LGTM.

**Review by goru97 — APPROVED** [review]
Let's wait for @mburns feedback, green signal from me.

**Review by mburns — APPROVED** [review]
thanks @itzg

**Pull request merged**
